name: Docs Build
on:{push:{branches:[ main ],paths:['marketing/**','legales/**','ops/templates/**']}}
jobs:{d:{runs-on: ubuntu-latest,steps:[{uses:'actions/checkout@v4'},{name:'Install pandoc',run:'sudo apt-get update && sudo apt-get install -y pandoc'},{name:'Render',run:'mkdir -p dist && pandoc marketing/posts/landing.md -f markdown -t docx -o dist/landing_$(date +%Y%m%d).docx'},{uses:'actions/upload-artifact@v4',with:{name:'docs_generados',path:'dist/*'}}]}}
