name: lae-latest-daily
on:
  workflow_dispatch: {}         # ← BOTÓN "Run workflow"
  schedule:
    - cron: "5 5 * * *"         # 05:05 UTC diario

permissions:
  contents: write

concurrency:
  group: lae-build-and-publish
  cancel-in-progress: false

jobs:
  latest:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PYTHONUNBUFFERED: "1"
      HEADLESS: "true"
      CONTROL_SHEET_ID: ${{ secrets.SHEETS_SPREADSHEET_ID }}
      GOOGLE_SA_JSON_BASE64: ${{ secrets.GOOGLE_SA_JSON_BASE64 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ops/scripts/requirements.txt || true
          pip install gspread google-auth
          pip install playwright
          python -m playwright install --with-deps chromium

      # LATEST (HTTP-only) → genera docs/api/*_latest.json
      - name: Fetch LAE latest (all games)
        run: |
          python ops/scripts/fetch_lae_runner.py --mode latest --games "primitiva,bonoloto,euromillones,gordo"

      - name: Commit & push JSON changes (latest)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/api/*.json || true
          if ! git diff --cached --quiet; then
            git commit -m "data: update LAE latest (all games)"
            git push
          else
            echo "No JSON changes (latest)."
          fi

      # Fallback Bonoloto (opcional). Si faltan secrets, se salta y no rompe.
      - name: Fallback Bonoloto (ayer) — opcional
        continue-on-error: true
        shell: bash
        run: |
          if [[ -z "${GOOGLE_SA_JSON_BASE64}" || -z "${CONTROL_SHEET_ID}" ]]; then
            echo "Skipping fallback: falta GOOGLE_SA_JSON_BASE64 o CONTROL_SHEET_ID"
            exit 0
          fi
          python ops/scripts/fetch_lae_results.py --game bonoloto --date "$(
            python - <<'PY'
from datetime import date, timedelta
print((date.today()-timedelta(days=1)).isoformat())
PY
          )"
