name: Deploy DQ Panel to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "ops/scripts/**"
      - "docs/**"
      - ".github/workflows/pages.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (ligero)
        run: |
          python -m pip install --upgrade pip
          pip install pandas python-dateutil

      - name: Build report.json + docs/index.html
        env:
          DIST_DIR: dist
        run: |
          python ops/scripts/make_report.py
          echo "JSON esperado en dist/report.json y HTML en docs/index.html"
          ls -l dist || true
          ls -l docs || true
          # Copiamos el JSON al folder que publicaremos (docs/)
          test -f dist/report.json || (echo "report.json faltante en dist/" && exit 1)
          mkdir -p docs
          cp dist/report.json docs/report.json
          echo "✓ Copiado dist/report.json → docs/report.json"

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
