name: Deploy DQ Panel to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "ops/scripts/**"
      - "docs/**"
      - ".github/workflows/pages.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (ligero)
        run: |
          python -m pip install --upgrade pip
          # sólo lo que pueda necesitar make_report.py
          pip install pandas python-dateutil

      - name: Build report.json + docs/index.html
        env:
          DIST_DIR: dist
        run: |
          python ops/scripts/make_report.py
          echo "✓ Generado $(pwd)/docs/index.html"
          test -f docs/report.json && echo "✓ report.json OK" || (echo "report.json faltante" && exit 1)

      # Empaquetar para Pages
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
