name: run-latest-now
'on':
  workflow_dispatch: {}
  schedule:
    - cron: "5 5 * * *"   # 05:05 UTC diario

permissions:
  contents: write
jobs:
  latest:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ops/scripts/requirements.txt || true
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Fetch LAE latest (HTTP, all games)
        run: |
          python ops/scripts/fetch_lae_runner.py --mode latest --games "primitiva,bonoloto,euromillones,gordo"

      - name: Commit & push JSON changes
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/api/*.json || true
          if ! git diff --cached --quiet; then
            git commit -m "data: update LAE latest (all games)"
            git push
          else
            echo "No JSON changes."
          fi
